vich_uploader:
    db_driver: orm

    mappings:
        avatar_image:
            uri_prefix: '%avatar_uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%avatar_uploads_path%'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
